import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Recognise the `_`-prefix convention for intentionally-unused identifiers.
  // The Next preset's @typescript-eslint/no-unused-vars defaults flag
  // anything unused, including catch-clause errors and interface-pinned
  // function parameters. We adopt the standard underscore-prefix opt-out so
  // patterns like `catch (_err) {}` and stub-provider signatures
  // (`async sendTemplate(_params: {...})`) lint cleanly without per-line
  // disables. Applied repo-wide; affects no runtime behaviour.
  {
    rules: {
      '@typescript-eslint/no-unused-vars': ['warn', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
        destructuredArrayIgnorePattern: '^_',
      }],
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by @ducanh2912/next-pwa — service worker + workbox runtime.
    // These are minified single-line files (~21-24 KB each on one line) that
    // produce hundreds of bogus lint errors when scanned. They're gitignored
    // (see .gitignore) but ESLint v9 flat config does not read .gitignore
    // automatically; the patterns must be mirrored here.
    "public/sw.js",
    "public/sw.js.map",
    "public/workbox-*.js",
    "public/workbox-*.js.map",
    "public/swe-worker-*.js",
  ]),
]);

export default eslintConfig;
