import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by @ducanh2912/next-pwa — service worker + workbox runtime.
    // These are minified single-line files (~21-24 KB each on one line) that
    // produce hundreds of bogus lint errors when scanned. They're gitignored
    // (see .gitignore) but ESLint v9 flat config does not read .gitignore
    // automatically; the patterns must be mirrored here.
    "public/sw.js",
    "public/sw.js.map",
    "public/workbox-*.js",
    "public/workbox-*.js.map",
    "public/swe-worker-*.js",
  ]),
]);

export default eslintConfig;
