import { NextResponse } from 'next/server'

// NOTE: Mentorship notifications are generated by the DB trigger
// `trg_on_mentorship_request` on INSERT into public.mentorship_requests.
// This route used to also send a notification, which caused duplicates.
// Kept as a 410 Gone so any stale clients fail loudly instead of double-notifying.
export async function POST() {
  return NextResponse.json(
    { error: 'Deprecated. Mentorship notifications are handled by the DB trigger.' },
    { status: 410 }
  )
}
